### PR TITLE
Fix PHP 8.4 property compatibility in ImportCommand and InitCommand

### LINKED ISSUE #10: PHP 8.4 incompatible $modelClass definition
PHP Version: 8.4.13
CakePHP Version: 5.2.8
Tinyauth-backend branch: master

Thanks for all your great work Mark - just a heads-up that under PHP 8.4.13 I get these two errors:

`TinyAuthBackend\Command\ImportCommand and Cake\Datasource\ModelAwareTrait define the same property ($modelClass) in the composition of TinyAuthBackend\Command\ImportCommand. However, the definition differs and is considered incompatible. Class was composed in /var/www/html/vendor/dereuromark/cakephp-tinyauth-backend/src/Command/ImportCommand.php on line 17`

`Fatal error: TinyAuthBackend\Command\InitCommand and Cake\Datasource\ModelAwareTrait define the same property ($modelClass) in the composition of TinyAuthBackend\Command\InitCommand. However, the definition differs and is considered incompatible. Class was composed in /var/www/html/vendor/dereuromark/cakephp-tinyauth-backend/src/Command/InitCommand.php on line 17`

The fix involves these two files:
- cakephp-tinyauth-backend\src\Command\ImportCommand.php
- cakephp-tinyauth-backend\src\Command\InitCommand.php

Change line 24 from:
`protected ?string $modelClass = 'TinyAuthBackend.AllowRules';`

To:
```
public function __construct() {
	parent::__construct();
	$this->modelClass = 'TinyAuthBackend.AllowRules';
}
```

### PR DESCRIPTION
**Pull request by Nicks18**
Fixes #10 

## Problem
Under PHP 8.4, the `$modelClass` property definition in `ImportCommand` and `InitCommand` conflicts with the same property in `ModelAwareTrait`, causing a fatal error:
> TinyAuthBackend\Command\ImportCommand and Cake\Datasource\ModelAwareTrait define the same property ($modelClass) in the composition of TinyAuthBackend\Command\ImportCommand. However, the definition differs and is considered incompatible.

## Solution
Moved the `$modelClass` initialization from the property declaration to the constructor in both files. This resolves the property compatibility issue while maintaining the same functionality.

## Changes
- `ImportCommand.php`: Initialize `$modelClass` in constructor instead of property declaration
- `InitCommand.php`: Initialize `$modelClass` in constructor instead of property declaration

### CODE REVIEW

File: src/Command/ImportCommand.php [hunk 1]
```diff
@@ -19,9 +19,12 @@ class ImportCommand extends Command {
 	use ModelAwareTrait;
 
 	/**
-	 * @var string|null
+	 * @inheritDoc
 	 */
-	protected ?string $modelClass = 'TinyAuthBackend.AllowRules';
```
Comment (dereuromark) [inline src/Command/ImportCommand.php:24]: you should just be using $defaultTable IMO, as those are the cake5 correct ones afaik.
And remove ModelAwareTrait etc.

Comment (dereuromark) [reply src/Command/ImportCommand.php:24]: See e.g. https://github.com/dereuromark/cakephp-sandbox/blob/044b4b064806c5b5eeab605bd017859ed26e12dd/plugins/Sandbox/src/Controller/CommentExamplesController.php#L15
